# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='End_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 11, 25, 2, 855386)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Start_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 25, 2, 855362)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 25, 2, 853873)),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 25, 2, 854904)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='Sub_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 25, 2, 855881)),
        ),
    ]
