# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170922_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='End_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 11, 35, 3, 129718)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Start_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 35, 3, 129694)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 35, 3, 128127)),
        ),
        migrations.AlterField(
            model_name='department',
            name='Head_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Personnel'),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 35, 3, 129236)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='Sub_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 11, 35, 3, 130221)),
        ),
    ]
