# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170922_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='End_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 3, 59, 54, 700700)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Start_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 3, 59, 54, 700658)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 3, 59, 54, 698225)),
        ),
        migrations.AlterField(
            model_name='department',
            name='Head_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Personnel'),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 3, 59, 54, 699834)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='Sub_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 3, 59, 54, 701569)),
        ),
    ]
