# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 04:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170922_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Head_ID',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='End_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 4, 5, 42, 797083)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Start_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 5, 42, 797038)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 5, 42, 794621)),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 5, 42, 796261)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='Sub_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 5, 42, 797934)),
        ),
    ]
