# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171014_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='Year',
            field=models.IntegerField(default=2013),
        ),
        migrations.AddField(
            model_name='submissions',
            name='Sub_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 19, 19, 70462)),
        ),
        migrations.AlterField(
            model_name='attendance_session',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 19, 19, 69338)),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 19, 19, 72952)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='End_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
