# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171020_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_time', models.IntegerField(choices=[(15, 15), (30, 30), (60, 60), (120, 120)], default=30)),
                ('Personnel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Personnel')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 5, 6, 20, 340800)),
        ),
        migrations.AlterField(
            model_name='attendance_session',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 5, 6, 20, 339851)),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 5, 6, 20, 342359)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='End_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Start_time',
            field=models.TimeField(),
        ),
    ]
