# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171104_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='RollNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 17, 10, 454836)),
        ),
        migrations.AlterField(
            model_name='attendance_session',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 17, 10, 453874)),
        ),
        migrations.AlterField(
            model_name='instructors_courses',
            name='End_Date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AlterField(
            model_name='instructors_courses',
            name='Start_Date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 17, 10, 456454)),
        ),
        migrations.AlterField(
            model_name='students_courses',
            name='Reg_Date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
    ]
