# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 04:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170922_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='End_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 4, 39, 24, 68890)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Start_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 39, 24, 68843)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 39, 24, 66307)),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 39, 24, 67948)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='Sub_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 4, 39, 24, 69780)),
        ),
    ]
