# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170922_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Assignment_File',
            field=models.FileField(default='hello.pdf', upload_to='AssignmentsFolder/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='End_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 5, 5, 36, 712005)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Start_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 5, 5, 36, 711901)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 5, 5, 36, 675996)),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 5, 5, 36, 693137)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='Sub_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 5, 5, 36, 729662)),
        ),
    ]
